language: ruby
rvm:
  - 2.2.3
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database auction_house_test' -U postgres
  - bundle exec rake db:restart RAIL_ENV=test
addons:
  postgresql: '9.3'