# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d0ddc25a7de658a314763c6f905a7d08abc2146dfe12fb90ca888f2596da347a439fd3fb315a1873241503b6dc647f59dfb662c2d4b137b80c9c081c2a331dc

test:
  secret_key_base: 491517585b099f40c583b506e791206ba8f1c8e2d20144579c64af7b59e270cdc5032274d25dda8c6465c94413f7a5b24b49e3185cc6171a410f7555d241e63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
